version: '3.8'

services:
  lufs-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Frontend dev server
      - "3001:3001"  # Backend server
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules
    working_dir: /app
    command: npm run dev
    restart: unless-stopped
